version: '2'
services:
  ubid-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/ubid/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ubid
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
